check again for existing PRs exactly before opening draft PR
also, add a notice regarding the permissions requested by gh auth

diff --git a/scripts/contribute b/scripts/contribute
--- a/scripts/contribute
+++ b/scripts/contribute
@@ -85,6 +85,7 @@ prompt_env_inputs() {
     echo
     echo "Now you need to login to your GitHub account to authenticate the process."
     echo " - During this process, you will be asked to login to your GitHub account using your browser."
+    echo " - You'll note the permissions requested are excessive, that's a limitation of how gh cli auth works, we can't do much about."
     echo " - The script will try to open your default browser, but it will fail."
     echo " - Don't worry, just copy the URL shown in the terminal and paste it in your browser."
     echo "Then, copy the code shown in the terminal and paste it in the browser."
@@ -136,6 +137,13 @@ check_contribute_env() {
         echo "You've already contributed to this zk-voceremony in file $CURRENT_CONTRIBUTION_FILE"
         echo "Contributing more than once is not allowed. Aborting..."
         exit 1
+    fi
+
+    echo
+    if curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$GITHUB_REPO/pulls" \
+    | jq '.[].title' | grep Contribution | grep $CEREMONY_BRANCH ; then
+      echo "Oops, there's a PR from someone *right now* uploading a contribution to this ceremony, just wait a couple of minutes and try again"
+      exit 5
     fi
 
     touch .lock && git add .lock && git commit .lock -m "Prevent other contributions" && git push origin $CEREMONY_BRANCH
